# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "https://ijkzen.github.io"
title = "IJKZEN"
enableRobotsTXT = true
enableEmoji = true
theme = "PaperMod"

[params.assets]
disableHLJS = true

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
style = "monokai"

[params]
ShowBreadCrumbs = true
ShowToc = true
ShowCodeCopyButtons = true

